FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY src ./src
COPY scripts ./scripts
COPY data ./data

ENV PORT=8090
ENV NODE_ENV=production

EXPOSE 8090
CMD ["npm", "start"]
